name: either_plus
description: Either with AppError class for Dart.
version: 1.0.0
repository: https://github.com/xRockmetalx26/either_plus

environment:
  sdk: ^3.6.1

dependencies:

  # Architecture
  equatable: ^2.0.7
